#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD7574483BB57B18D (jr@jriddell.org)
#
Name     : plasma-workspace-wallpapers
Version  : 5.26.2
Release  : 72
URL      : https://download.kde.org/stable/plasma/5.26.2/plasma-workspace-wallpapers-5.26.2.tar.xz
Source0  : https://download.kde.org/stable/plasma/5.26.2/plasma-workspace-wallpapers-5.26.2.tar.xz
Source1  : https://download.kde.org/stable/plasma/5.26.2/plasma-workspace-wallpapers-5.26.2.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-3.0
Requires: plasma-workspace-wallpapers-data = %{version}-%{release}
Requires: plasma-workspace-wallpapers-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data

%description
No detailed description available

%package data
Summary: data components for the plasma-workspace-wallpapers package.
Group: Data

%description data
data components for the plasma-workspace-wallpapers package.


%package license
Summary: license components for the plasma-workspace-wallpapers package.
Group: Default

%description license
license components for the plasma-workspace-wallpapers package.


%prep
%setup -q -n plasma-workspace-wallpapers-5.26.2
cd %{_builddir}/plasma-workspace-wallpapers-5.26.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1667240790
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1667240790
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/plasma-workspace-wallpapers
cp %{_builddir}/plasma-workspace-wallpapers-%{version}/COPYING %{buildroot}/usr/share/package-licenses/plasma-workspace-wallpapers/7c203dee3a03037da436df03c4b25b659c073976 || :
cp %{_builddir}/plasma-workspace-wallpapers-%{version}/COPYING.LGPL3 %{buildroot}/usr/share/package-licenses/plasma-workspace-wallpapers/f45ee1c765646813b442ca58de72e20a64a7ddba || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/wallpapers/Altai/contents/images/1080x1920.png
/usr/share/wallpapers/Altai/contents/images/5120x2880.png
/usr/share/wallpapers/Altai/contents/screenshot.png
/usr/share/wallpapers/Altai/metadata.json
/usr/share/wallpapers/Autumn/contents/images/1280x1024.jpg
/usr/share/wallpapers/Autumn/contents/images/1280x800.jpg
/usr/share/wallpapers/Autumn/contents/images/1440x900.jpg
/usr/share/wallpapers/Autumn/contents/images/1600x1200.jpg
/usr/share/wallpapers/Autumn/contents/images/1638x1024.jpg
/usr/share/wallpapers/Autumn/contents/images/1680x1050.jpg
/usr/share/wallpapers/Autumn/contents/images/1920x1080.jpg
/usr/share/wallpapers/Autumn/contents/images/1920x1200.jpg
/usr/share/wallpapers/Autumn/contents/images/2560x1440.jpg
/usr/share/wallpapers/Autumn/contents/images/2560x1600.jpg
/usr/share/wallpapers/Autumn/contents/images/640x480.jpg
/usr/share/wallpapers/Autumn/contents/images/800x600.jpg
/usr/share/wallpapers/Autumn/contents/screenshot.jpg
/usr/share/wallpapers/Autumn/metadata.json
/usr/share/wallpapers/BytheWater/contents/images/1280x1024.jpg
/usr/share/wallpapers/BytheWater/contents/images/1280x800.jpg
/usr/share/wallpapers/BytheWater/contents/images/1440x900.jpg
/usr/share/wallpapers/BytheWater/contents/images/1600x1200.jpg
/usr/share/wallpapers/BytheWater/contents/images/1638x1024.jpg
/usr/share/wallpapers/BytheWater/contents/images/1680x1050.jpg
/usr/share/wallpapers/BytheWater/contents/images/1920x1080.jpg
/usr/share/wallpapers/BytheWater/contents/images/1920x1200.jpg
/usr/share/wallpapers/BytheWater/contents/images/2560x1440.jpg
/usr/share/wallpapers/BytheWater/contents/images/2560x1600.jpg
/usr/share/wallpapers/BytheWater/contents/images/640x480.jpg
/usr/share/wallpapers/BytheWater/contents/images/800x600.jpg
/usr/share/wallpapers/BytheWater/contents/screenshot.jpg
/usr/share/wallpapers/BytheWater/metadata.json
/usr/share/wallpapers/Canopee/contents/images/3840x2160.png
/usr/share/wallpapers/Canopee/contents/screenshot.png
/usr/share/wallpapers/Canopee/metadata.json
/usr/share/wallpapers/Cascade/contents/images/3840x2160.png
/usr/share/wallpapers/Cascade/contents/screenshot.png
/usr/share/wallpapers/Cascade/metadata.json
/usr/share/wallpapers/Cluster/contents/images/3840x2160.png
/usr/share/wallpapers/Cluster/contents/screenshot.png
/usr/share/wallpapers/Cluster/metadata.json
/usr/share/wallpapers/ColdRipple/contents/images/1280x1024.jpg
/usr/share/wallpapers/ColdRipple/contents/images/1280x800.jpg
/usr/share/wallpapers/ColdRipple/contents/images/1440x900.jpg
/usr/share/wallpapers/ColdRipple/contents/images/1600x1200.jpg
/usr/share/wallpapers/ColdRipple/contents/images/1638x1024.jpg
/usr/share/wallpapers/ColdRipple/contents/images/1680x1050.jpg
/usr/share/wallpapers/ColdRipple/contents/images/1920x1080.jpg
/usr/share/wallpapers/ColdRipple/contents/images/1920x1200.jpg
/usr/share/wallpapers/ColdRipple/contents/images/2560x1440.jpg
/usr/share/wallpapers/ColdRipple/contents/images/2560x1600.jpg
/usr/share/wallpapers/ColdRipple/contents/images/640x480.jpg
/usr/share/wallpapers/ColdRipple/contents/images/800x600.jpg
/usr/share/wallpapers/ColdRipple/contents/screenshot.jpg
/usr/share/wallpapers/ColdRipple/metadata.json
/usr/share/wallpapers/ColorfulCups/contents/images/2560x1600.jpg
/usr/share/wallpapers/ColorfulCups/contents/screenshot.jpg
/usr/share/wallpapers/ColorfulCups/metadata.json
/usr/share/wallpapers/DarkestHour/contents/images/1280x1024.jpg
/usr/share/wallpapers/DarkestHour/contents/images/1280x800.jpg
/usr/share/wallpapers/DarkestHour/contents/images/1440x900.jpg
/usr/share/wallpapers/DarkestHour/contents/images/1600x1200.jpg
/usr/share/wallpapers/DarkestHour/contents/images/1638x1024.jpg
/usr/share/wallpapers/DarkestHour/contents/images/1680x1050.jpg
/usr/share/wallpapers/DarkestHour/contents/images/1920x1080.jpg
/usr/share/wallpapers/DarkestHour/contents/images/1920x1200.jpg
/usr/share/wallpapers/DarkestHour/contents/images/2560x1440.jpg
/usr/share/wallpapers/DarkestHour/contents/images/2560x1600.jpg
/usr/share/wallpapers/DarkestHour/contents/images/640x480.jpg
/usr/share/wallpapers/DarkestHour/contents/images/800x600.jpg
/usr/share/wallpapers/DarkestHour/contents/screenshot.jpg
/usr/share/wallpapers/DarkestHour/metadata.json
/usr/share/wallpapers/Elarun/contents/images/2560x1600.png
/usr/share/wallpapers/Elarun/contents/screenshot.jpg
/usr/share/wallpapers/Elarun/metadata.json
/usr/share/wallpapers/EveningGlow/contents/images/1280x1024.jpg
/usr/share/wallpapers/EveningGlow/contents/images/1280x800.jpg
/usr/share/wallpapers/EveningGlow/contents/images/1440x900.jpg
/usr/share/wallpapers/EveningGlow/contents/images/1600x1200.jpg
/usr/share/wallpapers/EveningGlow/contents/images/1638x1024.jpg
/usr/share/wallpapers/EveningGlow/contents/images/1680x1050.jpg
/usr/share/wallpapers/EveningGlow/contents/images/1920x1080.jpg
/usr/share/wallpapers/EveningGlow/contents/images/1920x1200.jpg
/usr/share/wallpapers/EveningGlow/contents/images/2560x1440.jpg
/usr/share/wallpapers/EveningGlow/contents/images/2560x1600.jpg
/usr/share/wallpapers/EveningGlow/contents/images/640x480.jpg
/usr/share/wallpapers/EveningGlow/contents/images/800x600.jpg
/usr/share/wallpapers/EveningGlow/contents/screenshot.jpg
/usr/share/wallpapers/EveningGlow/metadata.json
/usr/share/wallpapers/FallenLeaf/contents/images/1280x1024.jpg
/usr/share/wallpapers/FallenLeaf/contents/images/1280x800.jpg
/usr/share/wallpapers/FallenLeaf/contents/images/1440x900.jpg
/usr/share/wallpapers/FallenLeaf/contents/images/1600x1200.jpg
/usr/share/wallpapers/FallenLeaf/contents/images/1638x1024.jpg
/usr/share/wallpapers/FallenLeaf/contents/images/1680x1050.jpg
/usr/share/wallpapers/FallenLeaf/contents/images/1920x1080.jpg
/usr/share/wallpapers/FallenLeaf/contents/images/1920x1200.jpg
/usr/share/wallpapers/FallenLeaf/contents/images/2560x1440.jpg
/usr/share/wallpapers/FallenLeaf/contents/images/2560x1600.jpg
/usr/share/wallpapers/FallenLeaf/contents/images/640x480.jpg
/usr/share/wallpapers/FallenLeaf/contents/images/800x600.jpg
/usr/share/wallpapers/FallenLeaf/contents/screenshot.jpg
/usr/share/wallpapers/FallenLeaf/metadata.json
/usr/share/wallpapers/Flow/contents/images/5120x2880.jpg
/usr/share/wallpapers/Flow/contents/images/720x1440.jpg
/usr/share/wallpapers/Flow/contents/images_dark/5120x2880.jpg
/usr/share/wallpapers/Flow/contents/images_dark/720x1440.jpg
/usr/share/wallpapers/Flow/contents/screenshot.png
/usr/share/wallpapers/Flow/metadata.json
/usr/share/wallpapers/FlyingKonqui/contents/images/1280x1024.png
/usr/share/wallpapers/FlyingKonqui/contents/images/1280x800.png
/usr/share/wallpapers/FlyingKonqui/contents/images/1440x900.png
/usr/share/wallpapers/FlyingKonqui/contents/images/1600x1200.png
/usr/share/wallpapers/FlyingKonqui/contents/images/1638x1024.png
/usr/share/wallpapers/FlyingKonqui/contents/images/1680x1050.png
/usr/share/wallpapers/FlyingKonqui/contents/images/1920x1080.png
/usr/share/wallpapers/FlyingKonqui/contents/images/1920x1200.png
/usr/share/wallpapers/FlyingKonqui/contents/images/2560x1440.png
/usr/share/wallpapers/FlyingKonqui/contents/images/2560x1600.png
/usr/share/wallpapers/FlyingKonqui/contents/images/640x480.png
/usr/share/wallpapers/FlyingKonqui/contents/images/800x600.png
/usr/share/wallpapers/FlyingKonqui/contents/screenshot.png
/usr/share/wallpapers/FlyingKonqui/metadata.json
/usr/share/wallpapers/Grey/contents/images/1280x1024.jpg
/usr/share/wallpapers/Grey/contents/images/1280x800.jpg
/usr/share/wallpapers/Grey/contents/images/1440x900.jpg
/usr/share/wallpapers/Grey/contents/images/1600x1200.jpg
/usr/share/wallpapers/Grey/contents/images/1638x1024.jpg
/usr/share/wallpapers/Grey/contents/images/1680x1050.jpg
/usr/share/wallpapers/Grey/contents/images/1920x1080.jpg
/usr/share/wallpapers/Grey/contents/images/1920x1200.jpg
/usr/share/wallpapers/Grey/contents/images/2560x1440.jpg
/usr/share/wallpapers/Grey/contents/images/2560x1600.jpg
/usr/share/wallpapers/Grey/contents/images/640x480.jpg
/usr/share/wallpapers/Grey/contents/images/800x600.jpg
/usr/share/wallpapers/Grey/contents/screenshot.jpg
/usr/share/wallpapers/Grey/metadata.json
/usr/share/wallpapers/Honeywave/contents/images/1080x1920.jpg
/usr/share/wallpapers/Honeywave/contents/images/5120x2880.jpg
/usr/share/wallpapers/Honeywave/contents/screenshot.png
/usr/share/wallpapers/Honeywave/metadata.json
/usr/share/wallpapers/IceCold/contents/images/5120x2880.png
/usr/share/wallpapers/IceCold/contents/screenshot.png
/usr/share/wallpapers/IceCold/metadata.json
/usr/share/wallpapers/Kite/contents/images/1280x1024.jpg
/usr/share/wallpapers/Kite/contents/images/1280x800.jpg
/usr/share/wallpapers/Kite/contents/images/1440x900.jpg
/usr/share/wallpapers/Kite/contents/images/1600x1200.jpg
/usr/share/wallpapers/Kite/contents/images/1638x1024.jpg
/usr/share/wallpapers/Kite/contents/images/1680x1050.jpg
/usr/share/wallpapers/Kite/contents/images/1920x1080.jpg
/usr/share/wallpapers/Kite/contents/images/1920x1200.jpg
/usr/share/wallpapers/Kite/contents/images/2560x1440.jpg
/usr/share/wallpapers/Kite/contents/images/2560x1600.jpg
/usr/share/wallpapers/Kite/contents/images/640x480.jpg
/usr/share/wallpapers/Kite/contents/images/800x600.jpg
/usr/share/wallpapers/Kite/contents/screenshot.jpg
/usr/share/wallpapers/Kite/metadata.json
/usr/share/wallpapers/Kokkini/contents/images/3840x2160.png
/usr/share/wallpapers/Kokkini/contents/screenshot.png
/usr/share/wallpapers/Kokkini/metadata.json
/usr/share/wallpapers/MilkyWay/contents/images/1080x1920.png
/usr/share/wallpapers/MilkyWay/contents/images/5120x2880.png
/usr/share/wallpapers/MilkyWay/contents/screenshot.png
/usr/share/wallpapers/MilkyWay/metadata.json
/usr/share/wallpapers/OneStandsOut/contents/images/1280x1024.jpg
/usr/share/wallpapers/OneStandsOut/contents/images/1280x800.jpg
/usr/share/wallpapers/OneStandsOut/contents/images/1440x900.jpg
/usr/share/wallpapers/OneStandsOut/contents/images/1600x1200.jpg
/usr/share/wallpapers/OneStandsOut/contents/images/1638x1024.jpg
/usr/share/wallpapers/OneStandsOut/contents/images/1680x1050.jpg
/usr/share/wallpapers/OneStandsOut/contents/images/1920x1080.jpg
/usr/share/wallpapers/OneStandsOut/contents/images/1920x1200.jpg
/usr/share/wallpapers/OneStandsOut/contents/images/2560x1440.jpg
/usr/share/wallpapers/OneStandsOut/contents/images/2560x1600.jpg
/usr/share/wallpapers/OneStandsOut/contents/images/640x480.jpg
/usr/share/wallpapers/OneStandsOut/contents/images/800x600.jpg
/usr/share/wallpapers/OneStandsOut/contents/screenshot.jpg
/usr/share/wallpapers/OneStandsOut/metadata.json
/usr/share/wallpapers/Opal/contents/images/3840x2160.png
/usr/share/wallpapers/Opal/contents/screenshot.png
/usr/share/wallpapers/Opal/metadata.json
/usr/share/wallpapers/PastelHills/contents/images/1280x1024.jpg
/usr/share/wallpapers/PastelHills/contents/images/1280x800.jpg
/usr/share/wallpapers/PastelHills/contents/images/1440x900.jpg
/usr/share/wallpapers/PastelHills/contents/images/1600x1200.jpg
/usr/share/wallpapers/PastelHills/contents/images/1638x1024.jpg
/usr/share/wallpapers/PastelHills/contents/images/1680x1050.jpg
/usr/share/wallpapers/PastelHills/contents/images/1920x1080.jpg
/usr/share/wallpapers/PastelHills/contents/images/1920x1200.jpg
/usr/share/wallpapers/PastelHills/contents/images/2560x1440.jpg
/usr/share/wallpapers/PastelHills/contents/images/3200x2000.jpg
/usr/share/wallpapers/PastelHills/contents/images/640x480.jpg
/usr/share/wallpapers/PastelHills/contents/images/800x600.jpg
/usr/share/wallpapers/PastelHills/contents/screenshot.jpg
/usr/share/wallpapers/PastelHills/metadata.json
/usr/share/wallpapers/Patak/contents/images/1080x1920.png
/usr/share/wallpapers/Patak/contents/images/5120x2880.png
/usr/share/wallpapers/Patak/contents/images_dark/3840x2160.png
/usr/share/wallpapers/Patak/contents/screenshot.png
/usr/share/wallpapers/Patak/metadata.json
/usr/share/wallpapers/Path/contents/images/1280x1024.jpg
/usr/share/wallpapers/Path/contents/images/1280x800.jpg
/usr/share/wallpapers/Path/contents/images/1440x900.jpg
/usr/share/wallpapers/Path/contents/images/1600x1200.jpg
/usr/share/wallpapers/Path/contents/images/1638x1024.jpg
/usr/share/wallpapers/Path/contents/images/1680x1050.jpg
/usr/share/wallpapers/Path/contents/images/1920x1080.jpg
/usr/share/wallpapers/Path/contents/images/1920x1200.jpg
/usr/share/wallpapers/Path/contents/images/2560x1440.jpg
/usr/share/wallpapers/Path/contents/images/2560x1600.jpg
/usr/share/wallpapers/Path/contents/images/640x480.jpg
/usr/share/wallpapers/Path/contents/images/800x600.jpg
/usr/share/wallpapers/Path/contents/screenshot.jpg
/usr/share/wallpapers/Path/metadata.json
/usr/share/wallpapers/SafeLanding/contents/images/1622x2880.jpg
/usr/share/wallpapers/SafeLanding/contents/images/5120x2880.jpg
/usr/share/wallpapers/SafeLanding/contents/screenshot.jpg
/usr/share/wallpapers/SafeLanding/metadata.desktop
/usr/share/wallpapers/Shell/contents/images/5120x2880.jpg
/usr/share/wallpapers/Shell/contents/images/720x1440.jpg
/usr/share/wallpapers/Shell/contents/screenshot.png
/usr/share/wallpapers/Shell/metadata.json
/usr/share/wallpapers/Volna/contents/images/5120x2880.jpg
/usr/share/wallpapers/Volna/contents/screenshot.png
/usr/share/wallpapers/Volna/metadata.json
/usr/share/wallpapers/summer_1am/contents/images/1280x1024.jpg
/usr/share/wallpapers/summer_1am/contents/images/1280x800.jpg
/usr/share/wallpapers/summer_1am/contents/images/1440x900.jpg
/usr/share/wallpapers/summer_1am/contents/images/1600x1200.jpg
/usr/share/wallpapers/summer_1am/contents/images/1638x1024.jpg
/usr/share/wallpapers/summer_1am/contents/images/1680x1050.jpg
/usr/share/wallpapers/summer_1am/contents/images/1920x1080.jpg
/usr/share/wallpapers/summer_1am/contents/images/1920x1200.jpg
/usr/share/wallpapers/summer_1am/contents/images/2560x1440.jpg
/usr/share/wallpapers/summer_1am/contents/images/2560x1600.jpg
/usr/share/wallpapers/summer_1am/contents/images/640x480.jpg
/usr/share/wallpapers/summer_1am/contents/images/800x600.jpg
/usr/share/wallpapers/summer_1am/contents/screenshot.jpg
/usr/share/wallpapers/summer_1am/metadata.json

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/plasma-workspace-wallpapers/7c203dee3a03037da436df03c4b25b659c073976
/usr/share/package-licenses/plasma-workspace-wallpapers/f45ee1c765646813b442ca58de72e20a64a7ddba
